#include "MCP_DAC.h"
#include "lib_util.h"


#define GET_DEV(x, y) abs((x-y)/(x+0.0001))

class UTFR_APPS_DAC {                      

    public:

        UTFR_APPS_DAC(uint8_t dataOut = 255, uint8_t clock = 255);
        void begin(int CS);
        void processThrottlePosition();

    private:

        MCP4911 DAC;                                    // UTFR_APPS_DAC contains our DAC object (UTFR_APPS_DAC is now a composite class)

                                                        // "Composite" simply means it has a member which is an object of another class type (MCP4911 here)
                                                            // Composition helps avoid multiple inheritance
                                                            // Multiple inheritance is dangerous - can lead to the diamond problem 
                                                            // Multiple inheritance is slow (chains of function pointers in compiled program) 
                                                            // Multiple inheritance takes up more space (Function lookup tables generated by compiler) 
                                                            
                                                        // Therefore, Composition is advantageous over inheritance for safety and performance reasons

        const int _kANALOG_MAX = 1023;
        const float _kAPPS_1_HIGH = 4.75;     
        const float _kAPPS_2_HIGH = 4.75;      
        const float _kAPPS_1_LOW = 1.25;       
        const float _kAPPS_2_LOW = 1.25;      

        const int _kTIME_ALLOWANCE = 100;               // DO NOT CHANGE: Maximum error time allowed by rules; milliseconds
        const float _kTHROTTLE_MAX_DEVIATION = 0.10;    // DO NOT CHANGE: Rule T.4.2.4
        const float _kOUTPUT_DEVIATION = 0.03;          // ** TO DO: Determine **
        const long _kBASE_TIME = -1;

        float _APPS_1_high = 0.0;            // These will be the digital conversions of the constant voltage values above        
        float _APPS_2_high = 0.0;            // Used to calculate APPS_output
        float _APPS_1_low = 0.0;
        float _APPS_2_low = 0.0; 

        int _DAC_CS = 7;
        int _APPS_1_in = 0;
        int _APPS_2_in = 0;                             // 0 - 1023
        int _APPS_output = 0;
        int _APPS_out_verify = 0;                       // 0 - 1023
        float _APPS_1_throttle = 0.0;
        float _APPS_2_throttle = 0.0;
        long _time_at_error = _kBASE_TIME;              // unsigned long type according to arduino docs, not sure about this
        unsigned long _time_now = 0;

        bool _throttle_good = false;
        bool _output_good = false;
        bool _exceed_time_allowance = false;
        bool _error_flag_set = false;

        static int getDeviation(int value_1, int value_2);
        void sendOutput();
        void reportError();
        void shutDown();
        int roundOutput(float value);
        float getDigital(float voltage);          // gets 10-bit digital representation of a float (voltage) 

};